[package]
name = "producer_cl"
version = "0.0.1"
edition = "2021"

[dependencies]
ocl = "0.19"
hex = "0.3.1"
rayon = "1.3.0"
serde = { version = "1", features = ["derive"] }

common = { path = "../common" }
clap = { version = "4.4.10", features = ["derive"] }
