[package]
name = "common"
version = "0.1.0"
edition = "2021"


[dependencies]
csv = "1.2.2"
serde = { version = "1.0.188", features = ["derive"] }
clap = { version = "4.4.10", features = ["derive"] }
